gsm:
  pwd: '${PWD:YWRtaW4%3D}'
  url:
    get: '${URL_GET:http://192.168.32.1/goform/goform_get_cmd_process}'
    post: '${URL_POST:http://192.168.32.1/goform/goform_set_cmd_process}'
    origin: '${HEADER_ORIGIN:http://192.168.32.1}'
    referer: '${HEADER_REFERER:http://192.168.32.1/index.html}'
server:
  port: '${PORT:8080}'