gsm:
  pwd: ${PWD:YWRtaW4%3D}
  url:
    get: ${URL_GET:http://192.168.32.1/goform/goform_get_cmd_process}
    post: ${URL_POST:http://192.168.32.1/goform/goform_set_cmd_process}
    origin: ${HEADER_ORIGIN:http://192.168.32.1}
    referer: ${HEADER_REFERER:http://192.168.32.1/index.html}

server:
  port: ${PORT:8080}

spring:
  jackson:
    serialization:
      indent_output: true
  application:
    name: modem-service
  zipkin:
    baseUrl: ${ZIPKIN_PORT:http://127.0.0.1:9411}
    enabled: ${ZIPKIN_ENABLED:false}

scheduled:
  task:
    phone: ${ADMIN_PHONE_NUMBER}
    low:
      level: ${MODEM_LOW_CHARGE_LEVEL:5}
    job:
      cron: ${SCHEDULER_CRONE:0 * * * * *}

management:
  endpoints:
    web:
      exposure:
        include: '*'